name: ci

on:
  push:
    branches: dev
# jobs:
#   build-container:
#     name: Build container
#     runs-on: ubuntu-latest
#     steps:
#       # - name: Checkout code
#       #   uses: actions/checkout@v3
#       # - name: Login to Docker Hub
#       #   uses: docker/login-action@v1
#       #   with:
#       #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
#       #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#       # - name: Build and push to Docker Hub
#       #   uses: docker/build-push-action@v2
#       #   with:
#       #     context: .
#       #     push: true
#       #     tags: klanarong/authentication-service:latest
#       - name: test connect server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{secrets.SSH_HOST}}
#           username: ${{secrets.SSH_NAME}}
#           key: ${{secrets.SSH_KEY}}
#           port: 22
#           script: |
#             docker pull klanarong/authentication-service
#             docker run -p 92:80 -d --name authen-service klanarong/authentication-service:latest
